version: '3.1'

services:
  mysql:
    image: mysql-api-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: starwars-api-db

  controle-financeiro-api:
    image: starwarsapi
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080
