-- MySQL Script generated by MySQL Workbench
-- Wed May 15 23:44:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema starwars-api-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starwars-api-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starwars-api-db` DEFAULT CHARACTER SET utf8 ;
USE `starwars-api-db` ;

-- -----------------------------------------------------
-- Table `starwars-api-db`.`planets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars-api-db`.`planets` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `CLIMATE` VARCHAR(45) NULL,
  `TERRAIN` VARCHAR(45) NULL,
  `FILMS` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
