FROM mysql:5.7.25

MAINTAINER Esmael Gonçalves Pains <esmael.goncalves@hotmail.com>

#ENV MYSQL_USER=root \
#    MYSQL_DATABASE=starwars-api-db \
#    MYSQL_ROOT_PASSWORD=password

ADD ./scripts/V1__create_starwars_api_db.sql /docker-entrypoint-initdb.d